# Generated by Django 4.2.11 on 2024-05-28 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('oid', models.IntegerField(primary_key=True, serialize=False)),
                ('fname', models.CharField(max_length=50)),
                ('lname', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('email', models.CharField(max_length=70)),
                ('addr', models.CharField(max_length=500)),
            ],
        ),
    ]
