# Generated by Django 4.2.11 on 2024-05-28 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='oid',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
